apiVersion: v1
kind: Pod
metadata:
  namespace: prod
  name: sample-pod
spec:
  containers:
  - name: nginx-server
    image: nginx:stable-alpine3.21-perl
    ports:
    - containerPort: 80
